spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_caju
    username: root
    password: somewordpress
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql.init.mode: always

client:
  account: http://localhost:8080
  benefit: http://localhost:8080
  merchant: http://localhost:8080
  wallet: http://localhost:8080

logging:
  level:
    com.github.gsantosc18.authorizer.application.usecase: DEBUG
    com.github.gsantosc18.authorizer.infraestruture.client: DEBUG
