version: '3.3'
services:
  mariadb:
    image: mariadb:10.5
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
#      - mariadb-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=s3cr3t3s
      - MYSQL_DATABASE=caju
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306

  app:
    image: gsantosc18/authorizer:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=caju
      - DB_USER=root
      - DB_PASSWORD=s3cr3t3s
      - DB_SHOW_SQL=true
      - DB_FORMAT_SQL=true
    depends_on:
      - mariadb

volumes:
  mariadb-data: